'use client';
import { useEffect, useState } from 'react';
import { Layers, Plus, ArrowUpRight, ArrowRight, Clock3, CalendarDays, Sparkles, BatteryMedium, Check, Pencil, Trash2, Heart, Leaf, ListChecks, Coffee, Download } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Checkbox } from '@/components/ui/checkbox';
import { Slider } from '@/components/ui/slider';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { dayKey, offsetDay, makePlan, validTask, validCheckIn, CATEGORIES, categoryFor, groupTasks, type Category, type Task, type CheckIn } from '@/lib/planner';
const KEY='loadless-v1';
const labels=['Very low','Low','Moderate','High','Very high'];
const duration=(m:number)=>{const d=Math.floor(m/1440),h=Math.floor((m%1440)/60),mins=m%60;return [d?`${d}d`:null,h?`${h}h`:null,mins||(!d&&!h)?`${mins}m`:null].filter(Boolean).join(' ');};
const timeParts=(m=30)=>({days:Math.floor(m/1440),hours:Math.floor((m%1440)/60),minutes:m%60});
const wellbeingFactor=(check:CheckIn|undefined)=>check?check.energy>=4&&check.stress<=2?1.2:check.stress>=4||check.energy<=2?.65:check.energy===3||check.stress===3?.85:1:1;
const displayDate=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'});
export default function Home(){
 const [today,setToday]=useState(dayKey());const [tasks,setTasks]=useState<Task[]>([]);const [checks,setChecks]=useState<CheckIn[]>([]);const [available,setAvailable]=useState(180);const [ready,setReady]=useState(false);const [message,setMessage]=useState('');const [storageError,setStorageError]=useState('');
 const [tab,setTab]=useState('tasks');const [modal,setModal]=useState(false);const [editing,setEditing]=useState<Task|null>(null);const [priority,setPriority]=useState('2');const [stress,setStress]=useState(3);const [energy,setEnergy]=useState(3);const [note,setNote]=useState('');const [deleted,setDeleted]=useState<Task|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const data=JSON.parse(raw);if(!Array.isArray(data.tasks)||!data.tasks.every(validTask)||!Array.isArray(data.checks)||!data.checks.every(validCheckIn))throw Error();setTasks(data.tasks);setChecks(data.checks);if(Number.isInteger(data.available)&&data.available>=15&&data.available<=720)setAvailable(data.available);const c=data.checks.find((c:CheckIn)=>c.date===dayKey());if(c){setStress(c.stress);setEnergy(c.energy);setNote(c.note);}}}catch{setStorageError('Saved data could not be read. Export any work from this session before closing.');}setReady(true);const id=setInterval(()=>setToday(dayKey()),30000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(!ready||storageError)return;try{localStorage.setItem(KEY,JSON.stringify({tasks,checks,available}));}catch{setStorageError('Your browser could not save these changes. Export your data before closing.');}},[tasks,checks,available,ready,storageError]);
 const check=checks.find(c=>c.date===today);const plan=makePlan(tasks,available,check,today);const pending=tasks.filter(t=>!t.done);const completed=tasks.length-pending.length;const factor=wellbeingFactor(check);const weekEnd=offsetDay(today,6);const weeklyWork=pending.filter(t=>t.due>=today&&t.due<=weekEnd).reduce((sum,t)=>sum+t.minutes,0);const weeklyCapacity=Math.max(1,Math.round(available*7*factor));const weeklyLoad=Math.round(weeklyWork/weeklyCapacity*100);const recoveryNudge=weeklyLoad>100||check?.stress===5||check?.energy===1?'Protect recovery first: plan sleep, real downtime, or one easy hangout before taking on more.':weeklyLoad>=90||check?.stress===4||check?.energy===2?'Your week is close to full. Move one task, reduce scope, and put a recovery block on the calendar.':weeklyLoad>=70?'Your week is getting full. Keep one open evening or a short reset outside the house.':check&&check.energy>=4&&check.stress<=2?'You have good fuel today. Keep the pace kind, and still leave space to recover.':'There is breathing room this week. Keep a small rest block so it stays that way.';const planGroups=CATEGORIES.map(category=>({category,blocks:plan.blocks.map((block,index)=>({...block,index})).filter(block=>categoryFor(block.task)===category)})).filter(group=>group.blocks.length>0);
 function openTask(t:Task|null=null){setEditing(t);setPriority(String(t?.priority??2));setModal(true);}
 function saveTask(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const minutes=Number(f.get('days'))*1440+Number(f.get('hours'))*60+Number(f.get('timeMinutes'));const task:Task={id:editing?.id??crypto.randomUUID(),title:String(f.get('title')).trim(),course:String(f.get('course')).trim(),category:String(f.get('category')) as Category,due:String(f.get('due')),minutes,priority:Number(priority),done:editing?.done??false};if(!validTask(task)){setMessage('Please enter a title, valid deadline, and 5 minutes to 7 days of remaining work.');return;}setTasks(ts=>editing?ts.map(t=>t.id===editing.id?task:t):[...ts,task]);setModal(false);setMessage(editing?'Task updated.':'Task added. Your daily plan has been updated.');}
 function saveCheck(){const c={date:today,stress,energy,note:note.trim()};setChecks(cs=>[...cs.filter(x=>x.date!==today),c].sort((a,b)=>a.date.localeCompare(b.date)));setMessage('Check-in saved. Your plan now reflects today’s energy.');}
 function sample(){setTasks([{id:crypto.randomUUID(),title:'Finish the research outline',course:'Research methods',due:today,minutes:60,priority:3,done:false},{id:crypto.randomUUID(),title:'Review lecture notes',course:'Data structures',due:offsetDay(today,1),minutes:45,priority:2,done:false},{id:crypto.randomUUID(),title:'Prepare the project presentation',course:'Group project',due:offsetDay(today,3),minutes:120,priority:3,done:false},{id:crypto.randomUUID(),title:'Read chapter four',course:'Psychology',due:offsetDay(today,5),minutes:30,priority:1,done:false}]);setMessage('Sample tasks loaded. You can edit or remove each one.');}
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify({tasks,checks,available},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='loadless-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_loadless_plan',title:'Read daily workload plan',description:'Read the current browser’s tasks and energy-adjusted daily plan without changing anything.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return{date:today,availableMinutes:available,budgetMinutes:plan.budget,unplannedMinutes:plan.unplanned,urgentGapMinutes:plan.urgentGap,weeklyCapacityPercent:weeklyLoad,recoveryNudge,blocks:plan.blocks.map(b=>({title:b.task.title,category:categoryFor(b.task),minutes:b.minutes,breakBefore:b.breakBefore}))};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[tasks,checks,available,today]);
 return <div className="shell"><header><a className="brand" href="/"><Layers/>LoadLess<span>STUDENT WORKSPACE</span></a><span className="local-label"><span className="status-dot"/> Your space. Your pace.</span></header><main><div className="heading"><div><p className="eyebrow">{new Date(today+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</p><h1>Make room for a lighter day.</h1><p>Your workload and wellbeing, in one place.</p></div><button className="primary" onClick={()=>openTask()} disabled={!ready}><Plus size={18}/>Add task</button></div>
 {storageError&&<p role="alert" className="warning">{storageError}</p>}
 <div className="dashboard"><section className="card hero"><div className="balance-top"><span className="eyebrow">TODAY’S BALANCE</span><span className="pill">{check?'Personalised to your check-in':'Ready when you are'}</span></div><div className="balance-body"><div><h2>{!pending.length?'A fresh start, at your pace.':plan.urgentGap?'Let’s give your day some space.':'A little focus. Room to breathe.'}</h2><p>{!pending.length?'Bring your tasks here. Turn a busy week into a manageable next step.':plan.urgentGap?`${duration(plan.urgentGap)} due today or overdue won’t fit. Consider reducing scope or asking for more time.`:`Your plan makes room for ${duration(plan.work)} of focused work, with breaks along the way.`}</p><button className="light" onClick={()=>setTab('plan')}>See my daily plan <ArrowUpRight size={18}/></button></div><div className="capacity-circle"><span>{duration(plan.budget)}</span><small>today’s capacity</small></div></div><div className="capacity-control"><label htmlFor="available">Time available today <span>including breaks</span></label><div><input id="available" type="number" min="15" max="720" step="15" value={available} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=15&&n<=720)setAvailable(n);}}/><span>min</span></div></div></section>
 <section className="card checkin"><div className="section-head"><span className="icon-tile"><Heart size={20}/></span><span className="tiny-badge">{check?'SAVED TODAY':'DAILY CHECK-IN'}</span></div><h2>How are you arriving today?</h2><p>Your plan can meet you where you are.</p><div className="slider-label"><label id="stress-label">Stress level</label><strong>{labels[stress-1]}</strong></div><Slider aria-labelledby="stress-label" min={1} max={5} step={1} value={[stress]} onValueChange={v=>setStress(Array.isArray(v)?v[0]:v)}/><div className="scale"><span>Very low</span><span>Very high</span></div><div className="slider-label"><label id="energy-label">Energy level</label><strong>{labels[energy-1]}</strong></div><Slider aria-labelledby="energy-label" min={1} max={5} step={1} value={[energy]} onValueChange={v=>setEnergy(Array.isArray(v)?v[0]:v)}/><div className="scale"><span>Very low</span><span>Very high</span></div><label className="sr-only" htmlFor="note">Optional check-in note</label><input className="note" id="note" maxLength={500} placeholder="Anything on your mind? (optional)" value={note} onChange={e=>setNote(e.target.value)}/><button className="primary full" disabled={!ready} onClick={saveCheck}>{check?'Update check-in':'Save check-in'}<ArrowRight size={16}/></button></section></div>
 <section className={`card recovery-card ${weeklyLoad>=100?'overloaded':weeklyLoad>=90?'near-full':''}`}><div><span className="tiny-badge">WEEKLY CAPACITY</span><h2>You’re at {weeklyLoad}% capacity this week.</h2><p>{duration(weeklyWork)} due by {displayDate(weekEnd)} against {duration(weeklyCapacity)} adjusted capacity.</p></div><div className="recovery-meter" aria-label={`Weekly capacity ${weeklyLoad}%`}><span style={{width:`${Math.min(weeklyLoad,140)/1.4}%`}}/></div><p>{recoveryNudge}</p></section>
 <div className="stats"><div><ListChecks/><span><strong>{pending.length}</strong> tasks on your plate</span></div><div><Clock3/><span><strong>{duration(plan.total)}</strong> remaining work</span></div><div><Check/><span><strong>{completed}</strong> tasks completed</span></div><div><BatteryMedium/><span><strong>{check?labels[check.energy-1]:'Not logged'}</strong> energy today</span></div></div>
 <div className="lower-grid"><section className="card work-card"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="workspace-tabs" variant="line"><TabsTrigger value="tasks">My tasks <span className="count">{tasks.length}</span></TabsTrigger><TabsTrigger value="plan">Daily plan</TabsTrigger><TabsTrigger value="history">Check-in history</TabsTrigger></TabsList>
 <TabsContent value="tasks"><div className="section-heading"><div><h2>One thing at a time.</h2><p>Grouped by category, then sorted by deadline and priority.</p></div><button className="icon-button" aria-label="Add a task" onClick={()=>openTask()}><Plus size={20}/></button></div>{!ready?<p>Opening your workspace…</p>:!tasks.length?<div className="empty"><span className="empty-icon"><Leaf size={30}/></span><h3>A clear space for a busy mind.</h3><p>Add your first task or explore a sample student week.</p><div className="empty-actions"><button className="primary" onClick={()=>openTask()}>Add your first task</button><button className="text-button" onClick={sample}>Try sample tasks <ArrowRight size={16}/></button></div></div>:<div className="task-list">{groupTasks(tasks).map(group=><section className="category-group" key={group.category} aria-label={`${group.category} tasks`}><div className="category-heading"><h3>{group.category} <span className="count">{group.tasks.length}</span></h3><span>{duration(group.tasks.filter(t=>!t.done).reduce((sum,t)=>sum+t.minutes,0))} remaining</span></div>{group.tasks.map(t=><div className={`task-row ${t.done?'done':''}`} key={t.id}><Checkbox aria-label={`Mark ${t.title} ${t.done?'incomplete':'complete'}`} checked={t.done} onCheckedChange={done=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,done}:x))}/><div className="task-main"><button className="task-title" onClick={()=>openTask(t)}>{t.title}</button><div className="task-meta"><span>{t.course||categoryFor(t)}</span><span><Clock3 size={12}/>{duration(t.minutes)}</span><span className={!t.done&&t.due<today?'overdue':''}>{t.due<today&&!t.done?'Overdue · ':t.due===today?'Today · ':''}{displayDate(t.due)}</span></div></div><span className={`priority priority-${t.priority}`}>{['','Low','Medium','High'][t.priority]}</span><button className="icon-button edit-button" aria-label={`Edit ${t.title}`} onClick={()=>openTask(t)}><Pencil size={15}/></button></div>)}</section>)}</div>}</TabsContent>
 <TabsContent value="plan"><div className="section-heading"><div><h2>Your next manageable steps.</h2><p>{duration(plan.work)} work + {duration(plan.used-plan.work)} breaks</p></div><Coffee size={23}/></div><div className="plan-explanation">{check?`Today’s check-in uses ${Math.round(plan.factor*100)}% of your available time.`:'Save a check-in to adjust this plan to your energy.'} Tasks are split by category into blocks of up to 25 minutes, with 5-minute breaks.</div>{plan.urgentGap>0&&<p className="warning">{duration(plan.urgentGap)} due today or overdue cannot fit. Your deadlines have not been changed.</p>}{!plan.blocks.length?<div className="empty"><Leaf/><h3>No work blocks needed.</h3><p>Add a task or enjoy the space you’ve made.</p></div>:<div className="plan-list grouped-plan">{planGroups.map(group=><section className="category-group plan-category" key={group.category} aria-label={`${group.category} plan`}><div className="category-heading"><h3>{group.category} <span className="count">{group.blocks.length}</span></h3><span>{duration(group.blocks.reduce((sum,b)=>sum+b.minutes,0))} planned</span></div><ol>{group.blocks.map(b=><li key={`${b.task.id}-${b.index}`}>{b.breakBefore>0&&<div className="break"><Coffee size={14}/>{duration(b.breakBefore)} break</div>}<div className="plan-block"><span className="block-number">{String(b.index+1).padStart(2,'0')}</span><div><strong>{b.task.title}</strong><p>{b.task.course&&b.task.course!==categoryFor(b.task)?`${b.task.course} · `:''}Due {displayDate(b.task.due)}</p></div><span>{duration(b.minutes)}</span></div></li>)}</ol></section>)}</div>}{plan.unplanned>0&&<p className="plan-explanation">{duration(plan.unplanned)} remains outside today’s plan. These tasks stay on your list; review their deadlines before postponing work.</p>}<p className="fine-print">Completing a block doesn’t mark the whole task done. Update its remaining estimate in My tasks as you work.</p></TabsContent>
 <TabsContent value="history"><div className="section-heading"><div><h2>Notice your own patterns.</h2><p>Your daily reflections, without a score to chase.</p></div><Heart size={22}/></div>{!checks.length?<div className="empty"><Heart/><h3>A little self-awareness starts here.</h3><p>Save today’s check-in to begin your history.</p></div>:<div className="history">{[...checks].reverse().map(c=><article key={c.date}><div><strong>{displayDate(c.date)}</strong><span>Stress {c.stress}/5 · Energy {c.energy}/5</span></div>{c.note&&<p>{c.note}</p>}</article>)}</div>}</TabsContent></Tabs></section>
 <aside className="side-stack"><section className="card week-card"><div className="section-head"><h2>The week ahead</h2><CalendarDays size={19}/></div><p>Remaining work by deadline</p><div className="week-bars">{Array.from({length:7},(_,i)=>{const d=offsetDay(today,i),mins=pending.filter(t=>t.due===d).reduce((s,t)=>s+t.minutes,0),max=Math.max(60,...Array.from({length:7},(_,j)=>pending.filter(t=>t.due===offsetDay(today,j)).reduce((s,t)=>s+t.minutes,0)));return <div className="day-bar" key={d}><span>{mins?duration(mins):'—'}</span><div className="bar-track"><div style={{height:`${mins/max*100}%`}} className={i===0?'current':''}/></div><span>{new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span></div>})}</div><div className="legend"><span className="status-dot"/> Today <span>Deadlines, not scheduled work</span></div></section><section className="gentle-note"><Sparkles size={21}/><h3>Progress has a pace.</h3><p>A plan is a starting point. Adjust your estimates as you learn, and leave a little space for yourself.</p></section></aside></div>
 <div className="feedback" role="status" aria-live="polite">{message}{deleted&&<button className="text-button" onClick={()=>{setTasks(ts=>[...ts,deleted]);setDeleted(null);setMessage('Task restored.');}}>Undo deletion</button>}</div><footer><span><Layers size={16}/>LoadLess <span>•</span> Saved in this browser only. Export to keep a copy.</span><button className="text-button" onClick={exportData}><Download size={15}/>Export data</button></footer><p className="fine-print">Check-ins are personal reflections. Capacity adjustments are planning rules, not a health assessment.</p></main>
 <Dialog open={modal} onOpenChange={setModal}><DialogContent className="task-dialog"><DialogTitle>{editing?'Edit task':'A little less on your mind.'}</DialogTitle><DialogDescription>{editing?'Update the task or its remaining work estimate.':'Give it a name, a deadline, and a realistic time estimate.'}</DialogDescription><form onSubmit={saveTask} key={editing?.id??'new'}><label>Task name<input name="title" required maxLength={120} defaultValue={editing?.title} placeholder="e.g. Finish the research outline" autoFocus/></label><label>Category<NativeSelect name="category" required defaultValue={editing?categoryFor(editing):'Academic'} className="category-select">{CATEGORIES.map(category=><NativeSelectOption key={category} value={category}>{category}</NativeSelectOption>)}</NativeSelect></label><label>Course or details (optional)<input name="course" maxLength={60} defaultValue={editing?.course} placeholder="e.g. Research methods or gym session"/></label><div className="form-grid"><label>Deadline<input type="date" name="due" required defaultValue={editing?.due??today}/></label><fieldset className="time-field"><legend>Time remaining</legend><div><label>Days<input name="days" type="number" min={0} max={7} step={1} required defaultValue={timeParts(editing?.minutes).days}/></label><label>Hours<input name="hours" type="number" min={0} max={23} step={1} required defaultValue={timeParts(editing?.minutes).hours}/></label><label>Minutes<input name="timeMinutes" type="number" min={0} max={59} step={5} required defaultValue={timeParts(editing?.minutes).minutes}/></label></div></fieldset></div><label id="priority-label">Priority</label><RadioGroup aria-labelledby="priority-label" value={priority} onValueChange={v=>setPriority(String(v))} className="priority-options">{['Low','Medium','High'].map((p,i)=><label key={p}><RadioGroupItem value={String(i+1)}/>{p}</label>)}</RadioGroup><div className="form-actions">{editing&&<button type="button" className="delete-button" onClick={()=>{setDeleted(editing);setTasks(ts=>ts.filter(t=>t.id!==editing.id));setModal(false);setMessage('Task removed.');}}><Trash2 size={16}/>Delete</button>}<button className="primary" type="submit">{editing?'Save changes':'Add task'}<Plus size={16}/></button></div></form></DialogContent></Dialog></div>
}
