'use client';
import { useEffect, useState } from 'react';
import { Layers, Plus, ArrowUpRight, ArrowRight, Clock3, CalendarDays, Sparkles, BatteryMedium, Check, Pencil, Trash2, Heart, Leaf, ListChecks, Coffee, Download } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { RoutineEditor } from '@/components/routine-editor';
import { routinePlan, freeWindows, validRoutine, clockLabel, loadColor, type Routine } from '@/lib/routine';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Calendar } from '@/components/ui/calendar';
import { Checkbox } from '@/components/ui/checkbox';
import { Slider } from '@/components/ui/slider';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { dayKey, offsetDay, rankTasks, makePlan, validTask, validCheckIn, CATEGORIES, categoryFor, groupTasks, type Category, type Task, type CheckIn } from '@/lib/planner';
const KEY='loadless-v1';
const labels=['Very low','Low','Moderate','High','Very high'];
const duration=(m:number)=>{const d=Math.floor(m/1440),h=Math.floor((m%1440)/60),mins=m%60;return [d?`${d}d`:null,h?`${h}h`:null,mins||(!d&&!h)?`${mins}m`:null].filter(Boolean).join(' ');};
const timeParts=(m=30)=>({days:Math.floor(m/1440),hours:Math.floor((m%1440)/60),minutes:m%60});
const wellbeingFactor=(check:CheckIn|undefined)=>check?check.energy>=4&&check.stress<=2?1.2:check.stress>=4||check.energy<=2?.65:check.energy===3||check.stress===3?.85:1:1;
const displayDate=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'});
export default function Home(){
 const [routine,setRoutine]=useState<Routine[]>([]);const [routineOpen,setRoutineOpen]=useState(false);const [now,setNow]=useState(()=>new Date());
 const [today,setToday]=useState(dayKey());const [tasks,setTasks]=useState<Task[]>([]);const [checks,setChecks]=useState<CheckIn[]>([]);const [available,setAvailable]=useState(180);const [ready,setReady]=useState(false);const [message,setMessage]=useState('');const [storageError,setStorageError]=useState('');
 const [selectedDate,setSelectedDate]=useState<Date|undefined>(()=>new Date(dayKey()+'T12:00:00'));
 const [tab,setTab]=useState('tasks');const [modal,setModal]=useState(false);const [editing,setEditing]=useState<Task|null>(null);const [priority,setPriority]=useState('2');const [stress,setStress]=useState(3);const [energy,setEnergy]=useState(3);const [note,setNote]=useState('');const [deleted,setDeleted]=useState<Task|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const data=JSON.parse(raw);if(!Array.isArray(data.tasks)||!data.tasks.every(validTask)||!Array.isArray(data.checks)||!data.checks.every(validCheckIn))throw Error();if(validRoutine(data.routine))setRoutine(data.routine);setTasks(data.tasks);setChecks(data.checks);if(Number.isInteger(data.available)&&data.available>=15&&data.available<=720)setAvailable(data.available);const c=data.checks.find((c:CheckIn)=>c.date===dayKey());if(c){setStress(c.stress);setEnergy(c.energy);setNote(c.note);}}}catch{setStorageError('Saved data could not be read. Export any work from this session before closing.');}setReady(true);const id=setInterval(()=>{setToday(dayKey());setNow(new Date());},30000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(!ready||storageError)return;try{localStorage.setItem(KEY,JSON.stringify({tasks,checks,available,routine}));}catch{setStorageError('Your browser could not save these changes. Export your data before closing.');}},[tasks,checks,available,routine,ready,storageError]);
 const check=checks.find(c=>c.date===today);const plan=routinePlan(tasks,routine,check,today,now.getHours()*60+now.getMinutes());const pending=tasks.filter(t=>!t.done);const completed=tasks.length-pending.length;const factor=wellbeingFactor(check);const weekEnd=offsetDay(today,6);const weeklyWork=pending.filter(t=>t.due>=today&&t.due<=weekEnd).reduce((sum,t)=>sum+t.minutes,0);const weeklyCapacity=Math.max(1,Math.round((routine.length?freeWindows(routine).reduce((sum,w)=>sum+w.end-w.start,0):0)*7*factor));const weeklyLoad=routine.length?Math.round(weeklyWork/weeklyCapacity*100):0;const recoveryNudge=weeklyLoad>100||check?.stress===5||check?.energy===1?'Protect recovery first: plan sleep, real downtime, or one easy hangout before taking on more.':weeklyLoad>=90||check?.stress===4||check?.energy===2?'Your week is close to full. Move one task, reduce scope, and put a recovery block on the calendar.':weeklyLoad>=70?'Your week is getting full. Keep one open evening or a short reset outside the house.':check&&check.energy>=4&&check.stress<=2?'You have good fuel today. Keep the pace kind, and still leave space to recover.':'There is breathing room this week. Keep a small rest block so it stays that way.';const planGroups=CATEGORIES.map(category=>({category,blocks:plan.blocks.map((block,index)=>({...block,index})).filter(block=>categoryFor(block.task)===category)})).filter(group=>group.blocks.length>0);
 const dueToday=pending.filter(t=>t.due<=today).reduce((sum,t)=>sum+t.minutes,0);
 const dailyLoad=plan.budget?Math.round(Math.max(dueToday,plan.used)/plan.budget*100):dueToday?100:0;
 const suggestedStart=(id:string)=>{const block=plan.blocks.find(b=>b.task.id===id);return !routine.length?'Set your routine to get a start time':block?`Suggested start: Today at ${clockLabel(block.start)}`:'No space left today - review your plan';};
 const recommended=rankTasks(tasks).slice(0,3);
 const dateTasks=rankTasks(tasks).filter(t=>t.due===dayKey(selectedDate??new Date(today+'T12:00:00')));
 function openTask(t:Task|null=null){if(!routine.length&&!t){setRoutineOpen(true);return;}setEditing(t);setPriority(String(t?.priority??2));setModal(true);}
 function saveTask(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const minutes=editing?.minutes??({1:30,2:60,3:120}[Number(f.get('difficulty'))]??60);const task:Task={id:editing?.id??crypto.randomUUID(),title:String(f.get('title')).trim(),course:String(f.get('course')).trim(),category:String(f.get('category')) as Category,due:String(f.get('due')),minutes,priority:Number(priority),difficulty:Number(f.get("difficulty")),done:editing?.done??false};if(!validTask(task)){setMessage('Please enter a title, valid deadline, priority, and difficulty.');return;}setTasks(ts=>editing?ts.map(t=>t.id===editing.id?task:t):[...ts,task]);setModal(false);setMessage(editing?'Task updated.':'Task added. Your daily plan has been updated.');}
 function saveCheck(){const c={date:today,stress,energy,note:note.trim()};setChecks(cs=>[...cs.filter(x=>x.date!==today),c].sort((a,b)=>a.date.localeCompare(b.date)));setMessage('Check-in saved. Your plan now reflects today’s energy.');}
 function sample(){if(!routine.length){setRoutineOpen(true);return;}setTasks([{id:crypto.randomUUID(),title:'Finish the research outline',course:'Research methods',due:today,minutes:60,priority:3,done:false},{id:crypto.randomUUID(),title:'Review lecture notes',course:'Data structures',due:offsetDay(today,1),minutes:45,priority:2,done:false},{id:crypto.randomUUID(),title:'Prepare the project presentation',course:'Group project',due:offsetDay(today,3),minutes:120,priority:3,done:false},{id:crypto.randomUUID(),title:'Read chapter four',course:'Psychology',due:offsetDay(today,5),minutes:30,priority:1,done:false}]);setMessage('Sample tasks loaded. You can edit or remove each one.');}
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify({tasks,checks,available,routine},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='loadless-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_loadless_plan',title:'Read daily workload plan',description:'Read the current browser’s tasks and energy-adjusted daily plan without changing anything.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return{date:today,availableMinutes:plan.available,budgetMinutes:plan.budget,unplannedMinutes:plan.unplanned,urgentGapMinutes:plan.urgentGap,weeklyCapacityPercent:weeklyLoad,recoveryNudge,blocks:plan.blocks.map(b=>({title:b.task.title,category:categoryFor(b.task),minutes:b.minutes,start:clockLabel(b.start),end:clockLabel(b.end),breakBefore:b.breakBefore}))};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[tasks,checks,available,today,routine,now]);
 return <div className="shell"><header><a className="brand" href="/"><Layers/>LoadLess<span>STUDENT WORKSPACE</span></a><span className="local-label"><span className="status-dot"/> Your space. Your pace.</span></header><main><div className="heading"><div><p className="eyebrow">{new Date(today+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</p><h1>Make room for a lighter day.</h1><p>Your workload and wellbeing, in one place.</p></div><button className="primary" onClick={()=>openTask()} disabled={!ready}><Plus size={18}/>Add task</button></div>
 {storageError&&<p role="alert" className="warning">{storageError}</p>}
 <section className="card routine-intro"><div><h2>{routine.length?'Your day, with room for life.':'First, make room for your daily routine.'}</h2><p>{routine.length?`${routine.length} protected activities every day. Task start times use the free time remaining today.`:'Add sleep, meals, classes, and other commitments before creating tasks and generating a schedule.'}</p></div><button className="primary" disabled={!ready} onClick={()=>setRoutineOpen(true)}>{routine.length?'Edit routine':'Set up my routine'}</button></section><div className="dashboard"><section className="card hero"><div className="balance-top"><span className="eyebrow">TODAY’S BALANCE</span><span className="pill">{check?'Personalised to your check-in':'Ready when you are'}</span></div><div className="balance-body"><div><h2>{!pending.length?'A fresh start, at your pace.':plan.urgentGap?'Let’s give your day some space.':'A little focus. Room to breathe.'}</h2><p>{!pending.length?'Bring your tasks here. Turn a busy week into a manageable next step.':plan.urgentGap?`${duration(plan.urgentGap)} due today or overdue won’t fit. Consider reducing scope or asking for more time.`:`Your plan makes room for ${duration(plan.work)} of focused work, with breaks along the way.`}</p><button className="light" onClick={()=>setTab('plan')}>See my daily plan <ArrowUpRight size={18}/></button></div><div className="capacity-circle" style={{borderColor:loadColor(dailyLoad)}}><span style={{color:loadColor(dailyLoad)}}>{routine.length?`${dailyLoad}%`:'--'}</span><small>capacity used today</small></div></div><div className="capacity-control"><span>{routine.length?'Your routine protects meals, sleep, and downtime.':'Set your daily routine before adding tasks.'}</span><button className="light" onClick={()=>setRoutineOpen(true)}>{routine.length?'Edit daily routine':'Set daily routine'}</button></div></section>
 <section className="card checkin"><div className="section-head"><span className="icon-tile"><Heart size={20}/></span><span className="tiny-badge">{check?'SAVED TODAY':'DAILY CHECK-IN'}</span></div><h2>How are you arriving today?</h2><p>Your plan can meet you where you are.</p><div className="slider-label"><label id="stress-label">Stress level</label><strong>{labels[stress-1]}</strong></div><Slider aria-labelledby="stress-label" min={1} max={5} step={1} value={[stress]} onValueChange={v=>setStress(Array.isArray(v)?v[0]:v)}/><div className="scale"><span>Very low</span><span>Very high</span></div><div className="slider-label"><label id="energy-label">Energy level</label><strong>{labels[energy-1]}</strong></div><Slider aria-labelledby="energy-label" min={1} max={5} step={1} value={[energy]} onValueChange={v=>setEnergy(Array.isArray(v)?v[0]:v)}/><div className="scale"><span>Very low</span><span>Very high</span></div><label className="sr-only" htmlFor="note">Optional check-in note</label><input className="note" id="note" maxLength={500} placeholder="Anything on your mind? (optional)" value={note} onChange={e=>setNote(e.target.value)}/><button className="primary full" disabled={!ready} onClick={saveCheck}>{check?'Update check-in':'Save check-in'}<ArrowRight size={16}/></button></section></div>
 <section className={`card recovery-card ${weeklyLoad>=100?'overloaded':weeklyLoad>=90?'near-full':''}`}><div><span className="tiny-badge">WEEKLY CAPACITY</span><h2 style={{color:loadColor(weeklyLoad)}}>{routine.length?`You are at ${weeklyLoad}% capacity this week.`:"Set your routine to see weekly capacity."}</h2><p>{routine.length?`${duration(weeklyWork)} due by ${displayDate(weekEnd)} against ${duration(weeklyCapacity)} adjusted capacity.`:"Capacity will reflect your saved routine and check-in."}</p></div><div className="recovery-meter" aria-label={`Weekly capacity ${weeklyLoad}%`}><span style={{width:`${Math.min(weeklyLoad,100)}%`,background:loadColor(weeklyLoad)}}/></div><p>{routine.length?recoveryNudge:"Protect rest and everyday commitments first, then plan your work."}</p></section>
 <div className="stats"><div><ListChecks/><span><strong>{pending.length}</strong> tasks on your plate</span></div><div><Clock3/><span><strong>{duration(plan.total)}</strong> remaining work</span></div><div><Check/><span><strong>{completed}</strong> tasks completed</span></div><div><BatteryMedium/><span><strong>{check?labels[check.energy-1]:'Not logged'}</strong> energy today</span></div></div>
 <div className="lower-grid"><div className="work-stack"><section className="card next-task"><div className="section-head"><h2>What should I do first?</h2><Sparkles size={20}/></div><p>Earlier deadlines first, then higher priority, greater difficulty, and longer estimates.</p>{!recommended.length?<p>Add a task to get a suggested starting point.</p>:<ol className="recommendations">{recommended.map((t,i)=><li key={t.id}><span className="recommendation-number">{i+1}</span><div><button className="task-title" onClick={()=>openTask(t)}>{t.title}</button><p className={t.due<today?'overdue':''}>{t.due<today?'Overdue':t.due===today?'Due today':`Due ${displayDate(t.due)}`} | {['','Low','Medium','High'][t.priority]} priority | {['','Easy','Moderate','Hard'][t.difficulty??2]}</p><p><Clock3 size={14}/> Estimated effort: <strong>{duration(t.minutes)}</strong></p><p className="suggested-start">{suggestedStart(t.id)}</p></div></li>)}</ol>}{recommended.length>0&&<button className="text-button" onClick={()=>setTab('plan')}>View focus blocks and breaks <ArrowRight size={16}/></button>}</section><section className="card work-card"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="workspace-tabs" variant="line"><TabsTrigger value="tasks">My tasks <span className="count">{tasks.length}</span></TabsTrigger><TabsTrigger value="plan">Daily plan</TabsTrigger><TabsTrigger value="history">Check-in history</TabsTrigger></TabsList>
 <TabsContent value="tasks"><div className="section-heading"><div><h2>One thing at a time.</h2><p>Grouped by category, then sorted by deadline and priority.</p></div><button className="icon-button" aria-label="Add a task" onClick={()=>openTask()}><Plus size={20}/></button></div>{!ready?<p>Opening your workspace…</p>:!tasks.length?<div className="empty"><span className="empty-icon"><Leaf size={30}/></span><h3>A clear space for a busy mind.</h3><p>Add your first task or explore a sample student week.</p><div className="empty-actions"><button className="primary" onClick={()=>openTask()}>Add your first task</button><button className="text-button" onClick={sample}>Try sample tasks <ArrowRight size={16}/></button></div></div>:<Accordion className="task-list" multiple>{groupTasks(tasks).map(group=><AccordionItem className="category-group" value={group.category} key={group.category}><AccordionTrigger className="category-heading"><span>{group.category} <span className="count">{group.tasks.length}</span></span><span>{duration(group.tasks.filter(t=>!t.done).reduce((sum,t)=>sum+t.minutes,0))} remaining</span></AccordionTrigger><AccordionContent>{group.tasks.map(t=><div className={`task-row ${t.done?'done':''}`} key={t.id}><Checkbox aria-label={`Mark ${t.title} ${t.done?'incomplete':'complete'}`} checked={t.done} onCheckedChange={done=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,done}:x))}/><div className="task-main"><button className="task-title" onClick={()=>openTask(t)}>{t.title}</button><div className="task-meta"><span>{t.course||categoryFor(t)}</span><span><Clock3 size={12}/>{duration(t.minutes)}</span><span>{["","Easy","Moderate","Hard"][t.difficulty??2]}</span><span className={!t.done&&t.due<today?'overdue':''}>{t.due<today&&!t.done?'Overdue · ':t.due===today?'Today · ':''}{displayDate(t.due)}</span></div></div><span className={`priority priority-${t.priority}`}>{['','Low','Medium','High'][t.priority]}</span><button className="icon-button edit-button" aria-label={`Edit ${t.title}`} onClick={()=>openTask(t)}><Pencil size={15}/></button></div>)}</AccordionContent></AccordionItem>)}</Accordion>}</TabsContent>
 <TabsContent value="plan"><div className="section-heading"><div><h2>Your schedule today</h2><p>{duration(plan.work)} work + {duration(plan.used-plan.work)} breaks</p></div><Coffee size={23}/></div>{!routine.length?<div className="empty"><h3>Start with your daily routine.</h3><p>Protect sleep, meals, and commitments before generating a plan.</p><button className="primary" onClick={()=>setRoutineOpen(true)}>Set daily routine</button></div>:<><p className="plan-explanation">Tasks use free time after the current time, with breaks between focus blocks. Your saved check-in leaves extra breathing room when energy is low or stress is high.</p>{plan.urgentGap>0&&<p className="warning">{duration(plan.urgentGap)} due today or overdue cannot fit. Review scope or deadlines.</p>}<ol className="plan-list">{plan.blocks.map((b,index)=><li key={`${b.task.id}-${index}`}><div className="plan-block"><span className="schedule-time">{clockLabel(b.start)} - {clockLabel(b.end)}</span><div><strong>{b.task.title}</strong><p>{categoryFor(b.task)} | Due {displayDate(b.task.due)}</p></div><span>{duration(b.minutes)}</span></div>{b.breakBefore>0&&<p className="fine-print">A {b.breakBefore}-minute break is reserved before this block.</p>}</li>)}</ol>{!plan.blocks.length&&<p>No task blocks fit or are needed today. Your routine stays protected.</p>}{plan.unplanned>0&&<p className="plan-explanation">{duration(plan.unplanned)} is not scheduled today. These tasks stay on your list.</p>}<h3>Protected daily routine</h3><ul className="routine-summary">{routine.map(r=><li key={r.id}><strong>{r.name}</strong><span>{r.start} - {r.end}{r.end<r.start?' (overnight)':''}</span></li>)}</ul></>}</TabsContent>
 <TabsContent value="history"><div className="section-heading"><div><h2>Notice your own patterns.</h2><p>Your daily reflections, without a score to chase.</p></div><Heart size={22}/></div>{!checks.length?<div className="empty"><Heart/><h3>A little self-awareness starts here.</h3><p>Save today’s check-in to begin your history.</p></div>:<div className="history">{[...checks].reverse().map(c=><article key={c.date}><div><strong>{displayDate(c.date)}</strong><span>Stress {c.stress}/5 · Energy {c.energy}/5</span></div>{c.note&&<p>{c.note}</p>}</article>)}</div>}</TabsContent></Tabs></section></div>
 <aside className="side-stack"><section className="card due-calendar"><div className="section-head"><h2>Due-date calendar</h2><CalendarDays size={20}/></div><p>Dots mark dates with unfinished tasks.</p><Calendar mode="single" required selected={selectedDate} onSelect={setSelectedDate} modifiers={{hasDeadline:pending.map(t=>new Date(t.due+'T12:00:00'))}} modifiersClassNames={{hasDeadline:'has-deadline'}} labels={{labelDayButton:(date)=>{const count=pending.filter(t=>t.due===dayKey(date)).length;return `${date.toLocaleDateString(undefined,{dateStyle:'full'})}${count?`, ${count} unfinished tasks due`:''}`;}}}/><div className="calendar-agenda" aria-live="polite"><h3>Due {displayDate(dayKey(selectedDate??new Date(today+'T12:00:00')))}</h3>{dateTasks.length?dateTasks.map(t=><button className="agenda-task" key={t.id} onClick={()=>openTask(t)}><strong>{t.title}</strong><span>{categoryFor(t)} | {duration(t.minutes)} | {['','Low','Medium','High'][t.priority]} priority</span></button>):<p>No unfinished tasks due on this date.</p>}</div></section><section className="card week-card"><div className="section-head"><h2>The week ahead</h2><CalendarDays size={19}/></div><p>Remaining work by deadline</p><div className="week-bars">{Array.from({length:7},(_,i)=>{const d=offsetDay(today,i),mins=pending.filter(t=>t.due===d).reduce((s,t)=>s+t.minutes,0),max=Math.max(60,...Array.from({length:7},(_,j)=>pending.filter(t=>t.due===offsetDay(today,j)).reduce((s,t)=>s+t.minutes,0)));return <div className="day-bar" key={d}><span>{mins?duration(mins):'—'}</span><div className="bar-track"><div style={{height:`${mins/max*100}%`}} className={i===0?'current':''}/></div><span>{new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span></div>})}</div><div className="legend"><span className="status-dot"/> Today <span>Deadlines, not scheduled work</span></div></section><section className="gentle-note"><Sparkles size={21}/><h3>Progress has a pace.</h3><p>A plan is a starting point. Adjust your estimates as you learn, and leave a little space for yourself.</p></section></aside></div>
 <div className="feedback" role="status" aria-live="polite">{message}{deleted&&<button className="text-button" onClick={()=>{setTasks(ts=>[...ts,deleted]);setDeleted(null);setMessage('Task restored.');}}>Undo deletion</button>}</div><footer><span><Layers size={16}/>LoadLess <span>•</span> Saved in this browser only. Export to keep a copy.</span><button className="text-button" onClick={exportData}><Download size={15}/>Export data</button></footer><p className="fine-print">Check-ins are personal reflections. Capacity adjustments are planning rules, not a health assessment.</p></main>
 <Dialog open={routineOpen} onOpenChange={setRoutineOpen}><DialogContent className="routine-dialog"><DialogTitle>Your daily routine</DialogTitle><DialogDescription>Protect your everyday commitments before planning tasks.</DialogDescription><RoutineEditor value={routine} onCancel={()=>setRoutineOpen(false)} onSave={rows=>{setRoutine(rows);setRoutineOpen(false);setTab('plan');setMessage('Routine saved. Your schedule has been regenerated.');}}/></DialogContent></Dialog>
 <Dialog open={modal} onOpenChange={setModal}><DialogContent className="task-dialog"><DialogTitle>{editing?'Edit task':'A little less on your mind.'}</DialogTitle><DialogDescription>{editing?'Update the task details. Its existing estimate is retained.':'Add a deadline, priority, and difficulty. Rough estimates: Easy 30m, Moderate 1h, Hard 2h.'}</DialogDescription><form onSubmit={saveTask} key={editing?.id??'new'}><label>Task name<input name="title" required maxLength={120} defaultValue={editing?.title} placeholder="e.g. Finish the research outline" autoFocus/></label><label>Category<NativeSelect name="category" required defaultValue={editing?categoryFor(editing):'Academic'} className="category-select">{CATEGORIES.map(category=><NativeSelectOption key={category} value={category}>{category}</NativeSelectOption>)}</NativeSelect></label><label>Course or details (optional)<input name="course" maxLength={60} defaultValue={editing?.course} placeholder="e.g. Research methods or gym session"/></label><div className="form-grid"><label>Deadline<input type="date" name="due" required defaultValue={editing?.due??today}/></label></div><label>Difficulty<NativeSelect name="difficulty" defaultValue={String(editing?.difficulty??2)} className="category-select"><NativeSelectOption value="1">Easy</NativeSelectOption><NativeSelectOption value="2">Moderate</NativeSelectOption><NativeSelectOption value="3">Hard</NativeSelectOption></NativeSelect></label><label id="priority-label">Priority</label><RadioGroup aria-labelledby="priority-label" value={priority} onValueChange={v=>setPriority(String(v))} className="priority-options">{['Low','Medium','High'].map((p,i)=><label key={p}><RadioGroupItem value={String(i+1)}/>{p}</label>)}</RadioGroup><div className="form-actions">{editing&&<button type="button" className="delete-button" onClick={()=>{setDeleted(editing);setTasks(ts=>ts.filter(t=>t.id!==editing.id));setModal(false);setMessage('Task removed.');}}><Trash2 size={16}/>Delete</button>}<button className="primary" type="submit">{editing?'Save changes':'Add task'}<Plus size={16}/></button></div></form></DialogContent></Dialog></div>
}
