'use client';
import {ReflectionCard} from './reflection-card';
import {recapCanvas,canvasFile} from '@/lib/visual-cards';
import {useEffect,useState} from 'react';
import {Coffee, Sparkles, BatteryMedium, Share2, Heart} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {CATEGORIES,offsetDay,type Task,type CheckIn} from '@/lib/planner';
import {routinePlan,freeWindows,clockLabel,type Routine} from '@/lib/routine';
import {type TimeLog} from './time-insights';
const duration=(m:number)=>`${Math.floor(m/60)?Math.floor(m/60)+'h ':''}${m%60}m`;
export function DailyLife({tasks,routine,check,today,from,logs,checks,onLogs,onCheck,onPlan,onShare,onRoutine}:{tasks:Task[];routine:Routine[];check?:CheckIn;today:string;from:number;logs:TimeLog[];checks:CheckIn[];onLogs:(l:TimeLog[])=>void;onCheck:(c:CheckIn)=>void;onPlan:()=>void;onShare:(draft:string,photo?:File)=>void;onRoutine:()=>void}){
 const [preview,setPreview]=useState(false),[rest,setRest]=useState(false),[recap,setRecap]=useState(false),[includeTime,setIncludeTime]=useState(true),[includeWins,setIncludeWins]=useState(true),[includeNotes,setIncludeNotes]=useState(false),[reflection,setReflection]=useState(check?.note??''),[message,setMessage]=useState('');
 const plan=routinePlan(tasks,routine,check,today,from),tired={date:today,stress:check?.stress??3,energy:2,note:check?.note??''},lighter=routinePlan(tasks,routine,tired,today,from),next=plan.blocks[0];
 const recovery=freeWindows(routine,from,today).flatMap(w=>{let cursor=w.start;const gaps:{start:number;end:number}[]=[];for(const b of lighter.blocks.filter(b=>b.start<w.end&&b.end>w.start)){if(b.start-cursor>=15)gaps.push({start:cursor,end:b.start});cursor=Math.max(cursor,b.end);}if(w.end-cursor>=15)gaps.push({start:cursor,end:w.end});return gaps;})[0];
 const monday=offsetDay(today,-((new Date(today+'T12:00:00').getDay()+6)%7)),[lastWeek,setLastWeek]=useState(false),start=lastWeek?offsetDay(monday,-7):monday,end=offsetDay(start,6),entries=logs.filter(l=>l.source!=='skipped'&&l.date>=start&&l.date<=end),wins=entries.filter(l=>l.taskId||l.source==='recovery');
 const notes=checks.filter(c=>c.date>=start&&c.date<=end&&c.note);
 const body=[`My LoadLess week | ${start} to ${end}`,includeTime?CATEGORIES.map(c=>{const m=entries.filter(l=>l.category===c).reduce((a,l)=>a+l.minutes,0);return m?`${c}: ${duration(m)}`:'';}).filter(Boolean).join('\n'):'',includeTime&&entries.some(l=>l.source==='estimate')?'Includes estimated time for completed tasks.':'',includeWins?`${wins.filter(l=>l.taskId).length} tasks finished. ${wins.filter(l=>l.source==='recovery').length} recovery moments.`:'',includeNotes?notes.map(c=>`${c.date}: ${c.note}`).join('\n'):''].filter(Boolean).join('\n\n');
 const cardData={range:`${start} - ${end}`,buckets:CATEGORIES.map(name=>({name,minutes:entries.filter(l=>l.category===name).reduce((a,l)=>a+l.minutes,0)})),tasks:wins.filter(l=>l.taskId).length,rest:wins.filter(l=>l.source==='recovery').length,wins:includeWins,time:includeTime,notes:includeNotes?notes.map(n=>n.note):[],estimated:includeTime&&entries.some(l=>l.source==='estimate'||l.source==='routine')};
 const [recapUrl,setRecapUrl]=useState('');const cardKey=JSON.stringify(cardData);
 useEffect(()=>{if(recap)try{setRecapUrl(recapCanvas(cardData).toDataURL('image/png'));}catch{setRecapUrl('');}},[recap,cardKey]);
 async function recapImage(){return canvasFile(recapCanvas(cardData),'my-loadless-week.png');}
 async function shareRecap(){try{const photo=await recapImage();onShare(`My week · ${start} — ${end}`+(includeNotes?'\n\n'+notes.map(n=>n.note).join('\n'):''),photo);setRecap(false);}catch{setMessage('Could not create the image. Your recap opened as an editable text draft.');onShare(body);setRecap(false);}}
 return <><section className="card daily-for-you"><div className="section-head"><h2><Sparkles size={19}/> For you</h2><button className="text-button" onClick={()=>setPreview(true)} disabled={!routine.length}><BatteryMedium size={17}/> Match my energy</button></div><p>{!routine.length?'Make room for meals, sleep, and your week first.':next?`${clockLabel(next.start)} · ${next.task.title} · ${duration(next.minutes)} focus, then recharge`:'No more focus blocks today. Make room to recharge.'}</p><div className="life-actions"><button className="primary" onClick={routine.length?onPlan:onRoutine}>{routine.length?'Open plan':'Set routine'}</button><button className="text-button" onClick={()=>setRest(true)}><Coffee size={17}/> Rest counts</button><button className="text-button" onClick={()=>setRecap(true)}><Share2 size={17}/> My week</button></div><details className="evening-reflection"><summary><Heart size={16}/> Evening reflection</summary><ReflectionCard key={today} date={today} note={check?.note??''} onSave={note=>onCheck({date:today,stress:check?.stress??3,energy:check?.energy??3,note})} onShare={onShare}/></details>{message&&<p role="status">{message}</p>}</section>
 <Dialog open={preview} onOpenChange={setPreview}><DialogContent className="task-dialog"><DialogTitle>Match my energy</DialogTitle><DialogDescription>A lighter plan preview. Due and overdue work stays first; deadlines stay unchanged.</DialogDescription><div className="energy-comparison"><div>Current<strong>{duration(plan.work)}</strong></div><div>Low energy<strong>{duration(lighter.work)}</strong></div></div>{lighter.urgentGap>0&&<p className="warning">{duration(lighter.urgentGap)} urgent work still cannot fit. Review those tasks before committing.</p>}<p>{recovery?`Recovery gap: ${clockLabel(recovery.start)}–${clockLabel(recovery.start+15)}. Try downtime or a short walk.`:'No 15-minute recovery gap available. Review commitments to make room.'}</p><button className="primary" onClick={()=>{onCheck(tired);setPreview(false);setMessage('Low-energy check-in applied. The plan leaves extra time free for recovery.');}}>Use lighter plan</button></DialogContent></Dialog>
 <Dialog open={rest} onOpenChange={setRest}><DialogContent className="task-dialog"><DialogTitle>Rest counts as progress</DialogTitle><DialogDescription>Record a recovery activity after you have done it.</DialogDescription><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),activity=String(f.get('activity'));onLogs([...logs,{id:crypto.randomUUID(),date:today,category:activity==='Time with friends'?'Social':'Health & Wellbeing',title:activity,minutes:Number(f.get('minutes')),source:'recovery'}]);setRest(false);setMessage('Time for yourself counts. Recovery added to your chart.');}}><label>Activity<NativeSelect name="activity"><NativeSelectOption>Downtime</NativeSelectOption><NativeSelectOption>Outdoor walk</NativeSelectOption><NativeSelectOption>Sleep</NativeSelectOption><NativeSelectOption>Time with friends</NativeSelectOption><NativeSelectOption>Quiet break</NativeSelectOption></NativeSelect></label><label>Minutes spent<input name="minutes" type="number" required min={1} max={1440} defaultValue={15}/></label><button className="primary">Record recovery</button></form></DialogContent></Dialog>
 <Dialog open={recap} onOpenChange={setRecap}><DialogContent className="task-dialog"><DialogTitle>Your weekly life recap</DialogTitle><DialogDescription>Choose your highlights. Preview, then share.</DialogDescription><NativeSelect aria-label="Recap week" value={lastWeek?'last':'this'} onChange={e=>setLastWeek(e.target.value==='last')}><NativeSelectOption value="this">This week</NativeSelectOption><NativeSelectOption value="last">Last week</NativeSelectOption></NativeSelect><div className="recap-options">{[[includeTime,setIncludeTime,'Category time'],[includeWins,setIncludeWins,'Small wins'],[includeNotes,setIncludeNotes,'My reflections']] .map(([checked,set,label])=><label key={String(label)}><Checkbox checked={Boolean(checked)} onCheckedChange={v=>(set as (b:boolean)=>void)(Boolean(v))}/>{String(label)}</label>)}</div>{recapUrl?<img className="recap-image" src={recapUrl} alt="Weekly recap with category ring chart, progress totals and selected reflections"/>:<p>Preparing your card…</p>}{!entries.length&&<p>No time recorded this week yet.</p>}<button className="primary" disabled={body.length>2000||!entries.length&&!includeNotes} onClick={()=>void shareRecap()}>Share card</button>{body.length>2000&&<p>Choose fewer reflections to keep the post under 2,000 characters.</p>}</DialogContent></Dialog></>;
}
