'use client';
import {useEffect,useState} from 'react';
import {Heart,ImagePlus,MessageCircle,Search,Send,UserPlus,Users,Globe,Check} from 'lucide-react';
import {CATEGORIES} from '@/lib/planner';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';

type GuestPost={id:string;name:string;username:string;body:string;category:string;created:number;likes:number;liked:boolean;comments:string[];photo?:string};
const KEY='loadless-guest-social-v1';
const seed:GuestPost[]=[
 {id:'sara-walk',name:'Sara',username:'sara_moves',body:'Finished my notes, then took a sunset walk 🌿',category:'Health & Wellbeing',created:Date.now()-42*60_000,likes:8,liked:false,comments:['That balance looks good!']},
 {id:'adam-study',name:'Adam',username:'adam_studies',body:'One focused hour with friends. Presentation is finally taking shape.',category:'Academic',created:Date.now()-2*60*60_000,likes:12,liked:false,comments:[]},
];
const stamp=(n:number)=>new Date(n).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
function Avatar({name}:{name:string}){return <span className="social-avatar" aria-hidden="true">{name.slice(0,1)}</span>;}

export function GuestSocialHome({initialDraft,initialPhoto,onDraftUsed}:{initialDraft?:string;initialPhoto?:File|null;onDraftUsed?:()=>void}){
 const [posts,setPosts]=useState<GuestPost[]>(seed),[body,setBody]=useState(''),[category,setCategory]=useState('Academic'),[photo,setPhoto]=useState(''),[comments,setComments]=useState<Record<string,boolean>>({}),[drafts,setDrafts]=useState<Record<string,string>>({}),[search,setSearch]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved)setPosts(JSON.parse(saved));}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(posts));}catch{}},[posts]);
 useEffect(()=>{if(initialDraft){setBody(initialDraft);setCategory('Health & Wellbeing');if(initialPhoto){const reader=new FileReader();reader.onload=()=>setPhoto(String(reader.result||''));reader.readAsDataURL(initialPhoto);}onDraftUsed?.();}},[initialDraft,initialPhoto,onDraftUsed]);
 function choosePhoto(file?:File){if(!file)return;if(file.size>900_000)return;const reader=new FileReader();reader.onload=()=>setPhoto(String(reader.result||''));reader.readAsDataURL(file);}
 function publish(e:React.FormEvent){e.preventDefault();const text=body.trim();if(!text)return;setPosts(p=>[{id:crypto.randomUUID(),name:'You',username:'guest',body:text,category,created:Date.now(),likes:0,liked:false,comments:[],photo:photo||undefined},...p]);setBody('');setPhoto('');}
 function like(id:string){setPosts(p=>p.map(x=>x.id===id?{...x,liked:!x.liked,likes:Math.max(0,x.likes+(x.liked?-1:1))}:x));}
 function comment(e:React.FormEvent,id:string){e.preventDefault();const text=(drafts[id]||'').trim();if(!text)return;setPosts(p=>p.map(x=>x.id===id?{...x,comments:[...x.comments,text]}:x));setDrafts(d=>({...d,[id]:''}));}
 return <div className="social-layout"><section className="social-feed"><div className="social-toolbar"><div><button className="icon-button" onClick={()=>setSearch(true)} title="Find friends" aria-label="Find friends"><Search/></button></div></div>
  <form className="card post-composer" onSubmit={publish}><div className="composer-top"><Avatar name="You"/><div><strong>You</strong><small>@guest</small></div><span className="post-audience"><Globe size={14}/> Demo</span></div><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={500} required aria-label="Your activity" placeholder="What made today yours?"/>{photo&&<div className="photo-preview"><img src={photo} alt="Your selected activity"/></div>}<div className="composer-actions"><NativeSelect aria-label="Activity category" value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(c=><NativeSelectOption key={c} value={c}>{c}</NativeSelectOption>)}</NativeSelect><label className="icon-button" title="Add photo"><ImagePlus size={22}/><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choosePhoto(e.target.files?.[0])}/></label><button className="primary" type="submit" disabled={!body.trim()}><Send size={16}/>Share</button></div></form>
  <div className="feed-tabs"><button aria-pressed="true"><Globe size={16}/>Community</button><button onClick={()=>setSearch(true)}><Users size={16}/>Friends</button></div>
  {posts.map(post=><article className="card activity-post" key={post.id}><div className="post-heading"><Avatar name={post.name}/><div><strong>{post.name}</strong><small>@{post.username} · <time>{stamp(post.created)}</time></small></div></div><span className="activity-category">{post.category}</span><p className="activity-body">{post.body}</p>{post.photo&&<img className="activity-photo" src={post.photo} alt={`${post.name}'s activity`}/>}<div className="post-actions"><button aria-pressed={post.liked} onClick={()=>like(post.id)}><Heart size={19} fill={post.liked?'currentColor':'none'}/>{post.likes}</button><button aria-expanded={!!comments[post.id]} onClick={()=>setComments(c=>({...c,[post.id]:!c[post.id]}))}><MessageCircle size={19}/>{post.comments.length}</button></div>{comments[post.id]&&<div className="comments-panel">{post.comments.map((item,i)=><div className="comment" key={i}><Avatar name={i?'You':'M'}/><div><strong>{i?'You':'Mira'}</strong><p>{item}</p></div></div>)}<form onSubmit={e=>comment(e,post.id)}><input value={drafts[post.id]||''} onChange={e=>setDrafts(d=>({...d,[post.id]:e.target.value}))} maxLength={200} required aria-label="Comment" placeholder="Leave encouragement…"/><button className="icon-button" aria-label="Post comment"><Send size={18}/></button></form></div>}</article>)}
 </section><aside className="social-sidebar"><section className="card social-profile"><Avatar name="You"/><h3>You</h3><p>@guest</p></section><section className="card"><h3><UserPlus size={19}/> Friends</h3><div className="person-row"><Avatar name="Sara"/><div><strong>Sara</strong><small>@sara_moves</small></div><Check size={18}/></div><div className="person-row"><Avatar name="Adam"/><div><strong>Adam</strong><small>@adam_studies</small></div><Check size={18}/></div></section><section className="social-note"><Heart size={20}/><h3>Everyday counts.</h3><p>Study, move, rest, connect.</p></section></aside>
 <Dialog open={search} onOpenChange={setSearch}><DialogContent className="task-dialog"><DialogTitle>Find friends</DialogTitle><DialogDescription>Guest preview</DialogDescription>{['Sara · @sara_moves','Adam · @adam_studies','Mira · @mira_rest'].map(name=><div className="person-row" key={name}><Avatar name={name}/><strong>{name}</strong><button className="icon-button" aria-label={`Add ${name}`}><UserPlus size={18}/></button></div>)}</DialogContent></Dialog></div>;
}
