'use client';
import {useState} from 'react';
import {Sun,Cloud,Heart,Leaf,Sparkles,Send,Lock} from 'lucide-react';
const moods=[{name:'Grateful',symbol:'♡',Icon:Heart,color:'#854066'},{name:'Growing',symbol:'❧',Icon:Leaf,color:'#246657'},{name:'Bright',symbol:'☀',Icon:Sun,color:'#875816'},{name:'Quiet',symbol:'☁',Icon:Cloud,color:'#455d8a'},{name:'Proud',symbol:'✦',Icon:Sparkles,color:'#63518e'}];
export function ReflectionCard({note,date,onSave,onShare}:{note:string;date:string;onSave:(note:string)=>void;onShare:(text:string,photo?:File)=>void}){
 const [text,setText]=useState(note),[mood,setMood]=useState(0),[busy,setBusy]=useState(false),[status,setStatus]=useState('');const selected=moods[mood],Icon=selected.Icon;
 async function share(){setBusy(true);try{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1080;const c=canvas.getContext('2d');if(!c)throw Error();c.fillStyle=selected.color;c.fillRect(0,0,1080,1080);c.fillStyle='#ffffff';c.textAlign='center';c.font='150px sans-serif';c.fillText(selected.symbol,540,245);c.font='bold 54px sans-serif';c.fillText(selected.name,540,340);c.font='34px sans-serif';let line='',y=440;for(const word of text.trim().split(/\s+/)){const next=line?line+' '+word:word;if(c.measureText(next).width>880&&line){c.fillText(line,540,y);y+=49;line=word;}else line=next;}if(line)c.fillText(line,540,y);c.font='24px sans-serif';c.fillText('LOADLESS  ·  '+date,540,1000);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error()),'image/png'));onShare(selected.name+(text.trim()?' · '+text.trim():''),new File([blob],'reflection.png',{type:'image/png'}));}catch{setStatus('Could not create the card. Please try again.');}finally{setBusy(false);}}
 return <section className="reflection-widget"><div className="mood-picker" role="group" aria-label="Reflection mood">{moods.map(({name,Icon},i)=><button type="button" key={name} title={name} aria-label={name} aria-pressed={mood===i} onClick={()=>setMood(i)}><Icon size={23}/></button>)}</div><div className="reflection-preview" style={{background:selected.color}}><Icon size={42}/><strong>{selected.name}</strong><textarea aria-label="Reflection" maxLength={280} value={text} onChange={e=>setText(e.target.value)} placeholder="A little moment from today…"/><small>{date}</small></div><div className="reflection-actions"><button type="button" className="icon-button" title="Save privately" aria-label="Save reflection privately" onClick={()=>{onSave(text.trim());setStatus('Saved privately.');}}><Lock size={18}/></button><button type="button" className="primary" disabled={busy} onClick={()=>void share()}><Send size={17}/> Post card</button></div><small>Preview in your feed before sharing with members.</small>{status&&<p role="status">{status}</p>}</section>;
}
