'use client';
import {CATEGORIES} from '@/lib/planner';
import {routineCategory} from '@/lib/scheduled-time';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {useState} from 'react';
import {type Routine,validRoutine} from '@/lib/routine';
const defaults:Routine[]=[{id:'sleep',name:'Sleep',start:'23:00',end:'07:00'},{id:'breakfast',name:'Breakfast',start:'08:00',end:'08:30'},{id:'lunch',name:'Lunch',start:'13:00',end:'14:00'},{id:'dinner',name:'Dinner',start:'19:00',end:'20:00'}];
export function RoutineEditor({value,onSave,onCancel}:{value:Routine[];onSave:(rows:Routine[])=>void;onCancel:()=>void}){
 const [rows,setRows]=useState(value.length?value:defaults),[error,setError]=useState('');
 function update(id:string,key:keyof Routine,value:string){setRows(rs=>rs.map(r=>r.id===id?{...r,[key]:value}:r));}
 return <form className="routine-form" onSubmit={e=>{e.preventDefault();if(!validRoutine(rows)||rows.some(r=>r.days?.length===0)){setError('Add at least one activity with a name and different start and end times.');return;}onSave(rows);}}><p>Your week repeats automatically. Select the days each activity starts; overnight activities continue into the next day. Edit anytime.</p>{rows.map(r=><div className="routine-row" key={r.id}><label>Activity<input required maxLength={60} value={r.name} onChange={e=>update(r.id,'name',e.target.value)}/></label><label>Start<input required type="time" value={r.start} onChange={e=>update(r.id,'start',e.target.value)}/></label><label>End<input required type="time" value={r.end} onChange={e=>update(r.id,'end',e.target.value)}/></label><label>Category<NativeSelect value={r.category??routineCategory(r)} onChange={e=>update(r.id,'category',e.target.value)}>{CATEGORIES.map(c=><NativeSelectOption key={c} value={c}>{c}</NativeSelectOption>)}</NativeSelect></label><div className="routine-days">{[1,2,3,4,5,6,0].map(day=><label key={day}><Checkbox checked={(r.days??[0,1,2,3,4,5,6]).includes(day)} onCheckedChange={checked=>setRows(rs=>rs.map(x=>x.id===r.id?{...x,days:checked?[...(x.days??[0,1,2,3,4,5,6]),day]:(x.days??[0,1,2,3,4,5,6]).filter(d=>d!==day)}:x))}/>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][day]}</label>)}</div><button type="button" className="text-button" aria-label={`Remove ${r.name||'activity'}`} onClick={()=>setRows(rs=>rs.filter(x=>x.id!==r.id))}>Remove</button></div>)}<button type="button" className="text-button" onClick={()=>setRows(rs=>[...rs,{id:crypto.randomUUID(),name:'',start:'09:00',end:'10:00'}])}>+ Add activity</button>{error&&<p role="alert">{error}</p>}<div className="form-actions"><button className="text-button" type="button" onClick={onCancel}>Cancel</button><button className="primary" type="submit">Save routine & generate plan</button></div></form>;
}
