'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,ImagePlus,Heart,MessageCircle,Send,UserPlus,Users,Globe,RefreshCw,X,Trash2,Pencil,Check} from 'lucide-react';
import {CATEGORIES} from '@/lib/planner';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Person={id:string;name:string;username:string;relation?:string};
type Post={id:string;author:string;name:string;username:string;body:string;category:string;photo:string|null;created:number;likes:number;comments:number;liked:number};
type Comment={id:string;author:string;name:string;username:string;body:string;created:number};
async function api(path='',body?:unknown){const response=await fetch('/api/social'+path,body?{method:'POST',body:body instanceof FormData?body:JSON.stringify(body),headers:body instanceof FormData?{}:{'Content-Type':'application/json'}}:{cache:'no-store'});const text=await response.text();let data;try{data=JSON.parse(text);}catch{data={error:text};}if(!response.ok)throw new Error(response.status===401?'SIGN_IN':data.error||'Unable to connect. Try again.');return data;}
const stamp=(n:number)=>new Date(n).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
function Avatar({name}:{name:string}){return <span className="social-avatar" aria-hidden="true">{name.trim().slice(0,1).toUpperCase()||'?'}</span>;}
function Comments({post,onAdded}:{post:string;onAdded:()=>void}){const [items,setItems]=useState<Comment[]>([]),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;api(`?action=comments&id=${encodeURIComponent(post)}`).then(d=>{if(active)setItems(d.comments);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[post]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('',{action:'comment',post,body:draft});setDraft('');const d=await api(`?action=comments&id=${encodeURIComponent(post)}`);setItems(d.comments);onAdded();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="comments-panel">{loading&&<p>Loading comments…</p>}{items.map(c=><div className="comment" key={c.id}><Avatar name={c.name}/><div><strong>{c.name} <small>@{c.username}</small></strong><p>{c.body}</p><time>{stamp(c.created)}</time></div></div>)}{!loading&&!items.length&&<p className="muted">Be the first to cheer them on.</p>}<form onSubmit={submit}><label className="sr-only" htmlFor={'comment-'+post}>Comment</label><input id={'comment-'+post} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={500} required placeholder="Leave a little encouragement…"/><button className="icon-button" type="submit" disabled={busy||!draft.trim()} aria-label="Post comment"><Send size={18}/></button></form>{error&&<p role="alert">{error}</p>}</div>;
}
export function SocialHome({onProfileSaved,initialDraft,initialPhoto,onDraftUsed}:{onProfileSaved?:()=>void;initialDraft?:string;initialPhoto?:File|null;onDraftUsed?:()=>void}={}){
 const [me,setMe]=useState<Person|null>(null),[posts,setPosts]=useState<Post[]>([]),[requests,setRequests]=useState<Person[]>([]),[next,setNext]=useState<number|null>(null),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[signIn,setSignIn]=useState(false);
 const [body,setBody]=useState(''),[category,setCategory]=useState('Academic'),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState(''),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState(''),[people,setPeople]=useState<Person[]>([]),[searched,setSearched]=useState(false),[searchBusy,setSearchBusy]=useState(false),[profileOpen,setProfileOpen]=useState(false),[comments,setComments]=useState<Record<string,boolean>>({}),[deleting,setDeleting]=useState<string|null>(null);
 useEffect(()=>{if(initialDraft){setBody(initialDraft);setCategory('Health & Wellbeing');if(initialPhoto)setPhoto(initialPhoto);onDraftUsed?.();}},[initialDraft]);
 const fileRef=useRef<HTMLInputElement>(null);const generation=useRef(0);
 useEffect(()=>{if(!photo){setPreview('');return;}const url=URL.createObjectURL(photo);setPreview(url);return()=>URL.revokeObjectURL(url);},[photo]);
 async function refresh(append=false){const token=++generation.current;setLoading(true);setError('');try{const d=await api(`?following=${filter==='friends'?1:0}${append&&next?`&before=${next}`:''}`);if(token!==generation.current)return;setMe(d.me);setRequests(d.requests);setPosts(old=>append?[...old,...d.posts.filter((p:Post)=>!old.some(x=>x.id===p.id))]:d.posts);setNext(d.next);setSignIn(false);}catch(e){if(token===generation.current){if((e as Error).message==='SIGN_IN')setSignIn(true);else setError((e as Error).message);}}finally{if(token===generation.current)setLoading(false);}}
 useEffect(()=>{void refresh();return()=>{generation.current++;};},[filter]);
 async function mutate(data:unknown,after?:()=>void){setBusy(true);setError('');try{await api('',data);after?.();await refresh();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function publish(e:React.FormEvent){e.preventDefault();const form=new FormData();form.set('body',body);form.set('category',category);if(photo)form.set('photo',photo);await mutate(form,()=>{setBody('');setPhoto(null);if(fileRef.current)fileRef.current.value='';});}
 async function search(e?:React.FormEvent){e?.preventDefault();setSearchBusy(true);setError('');try{const d=await api('?action=search&q='+encodeURIComponent(query));setPeople(d.people);setSearched(true);}catch(e){setError((e as Error).message);}finally{setSearchBusy(false);}}
 async function friend(person:Person,mode:string){if(await mutate({action:'friend',target:person.id,mode}))await search();}
 async function saveProfile(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:'profile',name:f.get('name'),username:f.get('username')})){setProfileOpen(false);onProfileSaved?.();}}
 const profileForm=<form className="profile-form" onSubmit={saveProfile}><label>Display name<input name="name" required minLength={2} maxLength={50} defaultValue={me?.name}/></label><label>Username<input name="username" required pattern="[a-z0-9_]{3,24}" minLength={3} maxLength={24} defaultValue={me?.username} placeholder="e.g. akma_runs"/><small>Lowercase letters, numbers, underscores. 3–24 characters.</small></label><button className="primary" disabled={busy} type="submit">Save profile</button></form>;
 return <div className="social-layout"><section className="social-feed"><div className="social-toolbar"><div><h2>Life, in good company.</h2><p>Small wins. Everyday moments.</p></div><div><button className="icon-button" onClick={()=>{setSearchOpen(true);}} title="Find friends" aria-label="Find friends"><Search/></button><button className="icon-button" onClick={()=>refresh()} disabled={loading} title="Refresh feed" aria-label="Refresh feed"><RefreshCw size={19}/></button></div></div>{error&&<p className="warning" role="alert">{error}<button className="text-button" onClick={()=>refresh()}>Retry feed</button></p>}
 {signIn?<section className="card social-empty"><Users size={36}/><h2>Join your people.</h2><p>Sign in to share activities and connect with friends.</p><a className="social-signin" href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a></section>:loading&&!me?<p role="status">Loading your community…</p>:me&&!me.username?<section className="card"><h2>Choose your username</h2><p>Friends can find you here. Your name, username, posts, and comments are visible to signed-in members.</p>{profileForm}</section>:me&&<><form className="card post-composer" onSubmit={publish}><div className="composer-top"><Avatar name={me.name}/><div><strong>{me.name}</strong><small>@{me.username}</small></div><span className="post-audience"><Globe size={14}/> Members</span></div><label className="sr-only" htmlFor="activity-body">Your activity</label><textarea id="activity-body" value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} required placeholder="What made today yours?"/>{preview&&<div className="photo-preview"><img src={preview} alt="Photo attached to your draft"/><button type="button" className="icon-button" aria-label="Remove photo" onClick={()=>{setPhoto(null);if(fileRef.current)fileRef.current.value='';}}><X/></button></div>}<div className="composer-actions"><NativeSelect aria-label="Activity category" value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(c=><NativeSelectOption key={c} value={c}>{c}</NativeSelectOption>)}</NativeSelect><input ref={fileRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" aria-label="Activity photo" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>5*1024*1024){setError('Choose a JPG, PNG, or WebP photo under 5 MB.');e.target.value='';return;}setPhoto(f??null);}}/><button type="button" className="icon-button" title="Add photo" aria-label="Add photo" onClick={()=>fileRef.current?.click()}><ImagePlus size={22}/></button><button className="primary" type="submit" disabled={busy||!body.trim()}><Send size={16}/>{busy?'Sharing…':'Share'}</button></div></form>
 <div className="feed-tabs" role="group" aria-label="Feed filter"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}><Globe size={16}/>Community</button><button aria-pressed={filter==='friends'} onClick={()=>setFilter('friends')}><Users size={16}/>Friends</button></div>{!loading&&!posts.length&&<section className="card social-empty"><Users size={32}/><h3>{filter==='friends'?'Your circle starts here.':'A fresh start for the community.'}</h3><p>{filter==='friends'?'Find a friend or share your first activity.':'Share an activity to start the feed.'}</p><button className="text-button" onClick={()=>setSearchOpen(true)}><Search size={16}/>Find friends</button></section>}
 {posts.map(post=><article className="card activity-post" key={post.id}><div className="post-heading"><Avatar name={post.name}/><div><strong>{post.name}</strong><small>@{post.username} · <time>{stamp(post.created)}</time></small></div>{post.author===me.id&&<button className="icon-button" title="Delete post" aria-label="Delete your post" disabled={busy} onClick={()=>setDeleting(post.id)}><Trash2 size={17}/></button>}</div><span className="activity-category">{post.category}</span><p className="activity-body">{post.body}</p>{post.photo&&<img className="activity-photo" src={'/api/social?action=photo&id='+encodeURIComponent(post.id)} alt={`${post.name}'s ${post.category.toLowerCase()} activity photo`} loading="lazy"/>}<div className="post-actions"><button disabled={busy} aria-pressed={!!post.liked} onClick={()=>mutate({action:'like',post:post.id,value:!post.liked})}><Heart size={19} fill={post.liked?'currentColor':'none'}/><span>{post.likes}</span><span className="sr-only"> likes</span></button><button aria-expanded={!!comments[post.id]} onClick={()=>setComments(c=>({...c,[post.id]:!c[post.id]}))}><MessageCircle size={19}/>{post.comments}<span className="sr-only"> comments</span></button></div>{comments[post.id]&&<Comments post={post.id} onAdded={()=>refresh()}/>}</article>)}{loading&&me&&<p role="status">Loading…</p>}{next&&<button className="text-button" disabled={loading} onClick={()=>refresh(true)}>Load more</button>}</>}
 </section><aside className="social-sidebar">{me?.username&&<section className="card social-profile"><Avatar name={me.name}/><h3>{me.name}</h3><p>@{me.username}</p><button className="text-button" onClick={()=>setProfileOpen(true)}><Pencil size={15}/>Edit profile</button></section>}<section className="card"><h3><UserPlus size={19}/> Friend requests</h3>{!requests.length?<p>No requests yet.</p>:requests.map(p=><div className="person-row" key={p.id}><div><strong>{p.name}</strong><small>@{p.username}</small></div><button className="icon-button" disabled={busy} aria-label={`Accept ${p.username}`} title="Accept" onClick={()=>friend(p,'accept')}><Check size={18}/></button><button className="icon-button" disabled={busy} aria-label={`Decline ${p.username}`} title="Decline" onClick={()=>friend(p,'remove')}><X size={18}/></button></div>)}</section><section className="social-note"><Heart size={20}/><h3>Everyday counts.</h3><p>A walk, a study session, or time to recharge. Share what matters to you.</p></section></aside>
 <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="task-dialog"><DialogTitle>Find friends</DialogTitle><DialogDescription>Search by username or display name.</DialogDescription><form className="friend-search" onSubmit={search}><input value={query} onChange={e=>{setQuery(e.target.value);setSearched(false);}} aria-label="Search username" placeholder="@username" maxLength={60} required/><button className="icon-button" type="submit" disabled={searchBusy} aria-label="Search"><Search size={20}/></button></form>{searchBusy?<p>Searching…</p>:searched&&!people.length?<p>No profiles found. Your friend needs to join and choose a username first.</p>:people.map(p=><div className="person-row" key={p.id}><Avatar name={p.name}/><div><strong>{p.name}</strong><small>@{p.username}</small></div><button className="text-button" disabled={busy||!me?.username} onClick={()=>friend(p,p.relation==='received'?'accept':p.relation==='friends'||p.relation==='sent'?'remove':'request')}>{p.relation==='friends'?'Remove friend':p.relation==='sent'?'Cancel request':p.relation==='received'?'Accept':'Add friend'}</button></div>)}{error&&<p role="alert">{error}</p>}</DialogContent></Dialog>
 <Dialog open={profileOpen} onOpenChange={setProfileOpen}><DialogContent className="task-dialog"><DialogTitle>Edit profile</DialogTitle><DialogDescription>Your profile is visible to members.</DialogDescription>{profileForm}{error&&<p role="alert">{error}</p>}</DialogContent></Dialog>
 <Dialog open={!!deleting} onOpenChange={value=>{if(!value)setDeleting(null);}}><DialogContent className="task-dialog"><DialogTitle>Delete this activity?</DialogTitle><DialogDescription>This removes its photo, likes, and comments.</DialogDescription><button className="primary" disabled={busy} onClick={()=>mutate({action:'delete',post:deleting},()=>setDeleting(null))}>Delete post</button></DialogContent></Dialog>
 </div>;
}
