import test from 'node:test';
import assert from 'node:assert/strict';
import ts from 'typescript';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('./progress.ts',import.meta.url),'utf8').replace("'./planner'",JSON.stringify(new URL('./planner.ts',import.meta.url).href));
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {completionLogs,validLog}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const task={id:'task',title:'Study',course:'',category:'Academic',minutes:1500,priority:3,due:'2026-09-13',done:false};
test('completion adds estimated category time once, including long tasks',()=>{const once=completionLogs([],task,true,'2026-09-12','log');assert.equal(once[0].minutes,1500);assert.equal(once[0].source,'estimate');assert.ok(validLog(once[0]));assert.deepEqual(completionLogs(once,task,true,'2026-09-12','log2'),once);});
test('reopening removes only linked completion, preserving recovery time',()=>{const rest={id:'rest',title:'Walk',category:'Fitness',date:'2026-09-12',minutes:20,source:'recovery'};const complete=completionLogs([rest],task,true,'2026-09-12','log');assert.deepEqual(completionLogs(complete,task,false,'2026-09-12','unused'),[rest]);});
test('duplicate completion does not overwrite corrected actual time',()=>{const logs=completionLogs([],task,true,'2026-09-12','log').map(l=>({...l,minutes:90,source:'actual'}));assert.deepEqual(completionLogs(logs,task,true,'2026-09-13','other'),logs);});
