import test from 'node:test';
import assert from 'node:assert/strict';
import ts from 'typescript';
import {readFileSync} from 'node:fs';
const compile=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
const planner=JSON.stringify(new URL('./planner.ts',import.meta.url).href);
const routine=compile(readFileSync(new URL('./routine.ts',import.meta.url),'utf8').replace("'./planner'",planner));
const {scheduledTime}=await import(compile(readFileSync(new URL('./scheduled-time.ts',import.meta.url),'utf8').replace("'./planner'",planner).replace("'./routine'",JSON.stringify(routine))));
test('routine chart clips overnight time to each day and never double counts overlaps',()=>{const r=[{id:'s',name:'Sleep',start:'23:00',end:'07:00',days:[1]},{id:'x',name:'Rest',start:'23:30',end:'23:59',days:[1]}];const logs=scheduledTime(r,[],undefined,'2026-09-20','2026-09-14','2026-09-15');assert.equal(logs.reduce((s,l)=>s+l.minutes,0),480);assert.equal(logs.filter(l=>l.date==='2026-09-15')[0].minutes,420);assert.equal(logs[0].category,'Health & Wellbeing');});
test('explicit routine category updates projected chart without changing logs',()=>{const logs=scheduledTime([{id:'x',name:'Movies',start:'18:00',end:'20:00',category:'Social'}],[],undefined,'2026-09-20','2026-09-14','2026-09-14');assert.equal(logs[0].category,'Social');assert.equal(logs[0].minutes,120);});

const scheduled=compile(readFileSync(new URL('./scheduled-time.ts',import.meta.url),'utf8').replace("'./planner'",planner).replace("'./routine'",JSON.stringify(routine)));
const {recordElapsedRoutines}=await import(compile(readFileSync(new URL('./automatic-time.ts',import.meta.url),'utf8').replace("'./planner'",planner).replace("'./routine'",JSON.stringify(routine)).replace("'./scheduled-time'",JSON.stringify(scheduled))));
test('automatic routine records only elapsed blocks once and preserves skipped entries',()=>{const rows=[{id:'meal',name:'Lunch',start:'12:00',end:'13:00',trackingFrom:new Date('2026-09-14T00:00:00').getTime()}];assert.equal(recordElapsedRoutines([],rows,new Date('2026-09-14T12:30:00')).length,0);const logs=recordElapsedRoutines([],rows,new Date('2026-09-14T13:01:00'));assert.equal(logs[0].minutes,60);assert.equal(logs[0].source,'routine');assert.strictEqual(recordElapsedRoutines(logs,rows,new Date('2026-09-14T14:00:00')),logs);const skipped=logs.map(l=>({...l,source:'skipped'}));assert.strictEqual(recordElapsedRoutines(skipped,rows,new Date('2026-09-14T14:00:00')),skipped);});
test('new routines never invent records before activation and stored history stays unchanged',()=>{const rows=[{id:'meal',name:'Lunch',start:'12:00',end:'13:00',trackingFrom:new Date('2026-09-14T14:00:00').getTime()}];assert.equal(recordElapsedRoutines([],rows,new Date('2026-09-14T15:00:00')).length,0);const logs=recordElapsedRoutines([],rows,new Date('2026-09-15T14:00:00'));assert.equal(logs.length,1);assert.equal(logs[0].date,'2026-09-15');assert.strictEqual(recordElapsedRoutines(logs,[],new Date('2026-09-16T14:00:00')),logs);});
