import {storage,identity,json,boundedBody,fail} from '@/lib/social-server';
import {CATEGORIES} from '@/lib/planner';
export async function GET(request:Request){try{
 const user=identity(request),{DB,BUCKET}=storage(),url=new URL(request.url),action=url.searchParams.get('action');const profile=await DB.prepare('SELECT id,name,username FROM profiles WHERE id=?').bind(user).first();if(!profile){if(action)return json({error:'Complete your profile first.'},403);return json({me:{id:user,name:'',username:''},posts:[],requests:[],next:null});}
 if(action==='photo'){const post=await DB.prepare('SELECT photo FROM posts WHERE id = ?').bind(url.searchParams.get('id')).first<{photo:string}>();if(!post?.photo)return new Response('Not found',{status:404});const file=await BUCKET.get(post.photo);if(!file)return new Response('Not found',{status:404});return new Response(file.body,{headers:{'Content-Type':file.httpMetadata?.contentType??'image/jpeg','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
 if(action==='search'){const query=(url.searchParams.get('q')??'').trim().replace(/^@/,'').slice(0,60);if(!query)return json({people:[]});const result=await DB.prepare("SELECT p.id,p.name,p.username,CASE WHEN EXISTS(SELECT 1 FROM follows f WHERE f.accepted=1 AND ((f.user=? AND f.target=p.id) OR (f.target=? AND f.user=p.id))) THEN 'friends' WHEN EXISTS(SELECT 1 FROM follows f WHERE f.user=? AND f.target=p.id) THEN 'sent' WHEN EXISTS(SELECT 1 FROM follows f WHERE f.target=? AND f.user=p.id) THEN 'received' ELSE 'none' END AS relation FROM profiles p WHERE p.id<>? AND (instr(lower(p.name),lower(?))>0 OR instr(p.username,lower(?))>0) ORDER BY p.username LIMIT 30").bind(user,user,user,user,user,query,query).all();return json({people:result.results});}
 if(action==='comments'){const result=await DB.prepare('SELECT c.id,c.body,c.created,c.author,p.name,p.username FROM comments c JOIN profiles p ON p.id=c.author WHERE c.post=? ORDER BY c.created DESC,c.id DESC LIMIT 100').bind(url.searchParams.get('id')).all();return json({comments:result.results.reverse()});}
 const me=profile;const before=Number(url.searchParams.get('before'))||Number.MAX_SAFE_INTEGER;const following=url.searchParams.get('following')==='1';
 const result=await DB.prepare(`SELECT p.rowid AS cursor,p.id,p.author,p.body,p.category,p.photo,p.created,u.name,u.username,(SELECT count(*) FROM likes l WHERE l.post=p.id) AS likes,(SELECT count(*) FROM comments c WHERE c.post=p.id) AS comments,EXISTS(SELECT 1 FROM likes l WHERE l.post=p.id AND l.user=?) AS liked FROM posts p JOIN profiles u ON p.author=u.id WHERE p.rowid<? ${following?'AND (p.author=? OR EXISTS(SELECT 1 FROM follows f WHERE f.accepted=1 AND ((f.user=? AND f.target=p.author) OR (f.target=? AND f.user=p.author))))':''} ORDER BY p.rowid DESC LIMIT 20`).bind(...(following?[user,before,user,user,user]:[user,before])).all();
 const requests=await DB.prepare('SELECT p.id,p.name,p.username FROM follows f JOIN profiles p ON p.id=f.user WHERE f.target=? AND f.accepted=0').bind(user).all();return json({requests:requests.results,me:me??{id:user,name:'',username:''},posts:result.results,next:result.results.length===20?result.results[result.results.length-1].cursor:null});
 }catch(e){return fail(e);}}
export async function POST(request:Request){try{
 const user=identity(request),{DB,BUCKET}=storage(),url=new URL(request.url);if(request.headers.get('origin')!==url.origin||request.headers.get('sec-fetch-site')==='cross-site')return json({error:'Request origin rejected'},403);
 const multipart=request.headers.get('content-type')?.startsWith('multipart/form-data');const bytes=await boundedBody(request,multipart?6*1024*1024:20000);
 if(multipart){const profile=await DB.prepare('SELECT id FROM profiles WHERE id=?').bind(user).first();if(!profile)return json({error:'Choose your display name first.'},400);const form=await new Response(bytes,{headers:{'Content-Type':request.headers.get('content-type')!}}).formData();const body=String(form.get('body')??'').trim(),category=String(form.get('category'));if(!body||body.length>2000||!CATEGORIES.includes(category as typeof CATEGORIES[number]))return json({error:'Add an activity description (up to 2,000 characters).'},400);
 const id=crypto.randomUUID(),photo=form.get('photo');let key:string|null=null;
 if(photo instanceof File&&photo.size){if(photo.size>5*1024*1024)return json({error:'Choose a photo under 5 MB.'},400);const data=new Uint8Array(await photo.arrayBuffer());const mime=data[0]===255&&data[1]===216&&data[2]===255?'image/jpeg':data[0]===137&&data[1]===80&&data[2]===78&&data[3]===71?'image/png':new TextDecoder().decode(data.slice(0,4))==='RIFF'&&new TextDecoder().decode(data.slice(8,12))==='WEBP'?'image/webp':null;if(!mime)return json({error:'Use a JPG, PNG, or WebP photo.'},400);key=`posts/${id}`;await BUCKET.put(key,data,{httpMetadata:{contentType:mime}});}
 try{await DB.prepare('INSERT INTO posts (id,author,body,category,photo,created) VALUES (?,?,?,?,?,?)').bind(id,user,body,category,key,Date.now()).run();}catch(e){if(key)await BUCKET.delete(key);throw e;}return json({ok:true});}
 const data=JSON.parse(new TextDecoder().decode(bytes));const action=data.action;
 if(action==='profile'){const name=String(data.name??'').trim(),username=String(data.username??'').trim().toLowerCase();if(name.length<2||name.length>50||!/^([a-z0-9_]){3,24}$/.test(username))return json({error:'Name: 2-50 characters. Username: 3-24 letters, numbers, or underscores.'},400);try{await DB.prepare('INSERT INTO profiles (id,name,username,created) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,username=excluded.username').bind(user,name,username,Date.now()).run();}catch(e){if(String(e).includes('UNIQUE'))return json({error:'That username is already taken.'},409);throw e;}return json({ok:true});}
 if(!await DB.prepare('SELECT id FROM profiles WHERE id=?').bind(user).first())return json({error:'Choose your display name first.'},400);
 if(action==='friend'){if(data.target===user)return json({error:'Choose another person.'},400);if(!await DB.prepare('SELECT id FROM profiles WHERE id=?').bind(data.target).first())return json({error:'Person not found'},404);if(data.mode==='accept')await DB.prepare('UPDATE follows SET accepted=1 WHERE user=? AND target=? AND accepted=0').bind(data.target,user).run();else if(data.mode==='remove')await DB.prepare('DELETE FROM follows WHERE (user=? AND target=?) OR (user=? AND target=?)').bind(user,data.target,data.target,user).run();else await DB.prepare('INSERT OR IGNORE INTO follows (user,target,accepted) SELECT ?,?,0 WHERE NOT EXISTS(SELECT 1 FROM follows WHERE user=? AND target=?)').bind(user,data.target,data.target,user).run();return json({ok:true});}
 if(!await DB.prepare('SELECT id FROM posts WHERE id=?').bind(data.post).first())return json({error:'Post no longer available'},404);
 if(action==='like'){await DB.prepare(data.value?'INSERT OR IGNORE INTO likes (post,user) VALUES (?,?)':'DELETE FROM likes WHERE post=? AND user=?').bind(data.post,user).run();return json({ok:true});}
 if(action==='comment'){const body=String(data.body??'').trim();if(!body||body.length>500)return json({error:'Write a comment of up to 500 characters.'},400);await DB.prepare('INSERT INTO comments (id,post,author,body,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),data.post,user,body,Date.now()).run();return json({ok:true});}
 if(action==='delete'){const post=await DB.prepare('SELECT photo FROM posts WHERE id=? AND author=?').bind(data.post,user).first<{photo:string|null}>();if(!post)return json({error:'Only the author can delete this post.'},403);await DB.prepare('DELETE FROM posts WHERE id=? AND author=?').bind(data.post,user).run();if(post.photo)await BUCKET.delete([post.photo]);return json({ok:true});}
 return json({error:'Unknown action'},400);
 }catch(e){return fail(e);}}

